name: Daily Commit

on:
  schedule:
    - cron: "0 6 * * 1-5"  # 08:00 Europe/Berlin in summer (UTC+2). Use 7 in winter if you care.
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Add new line
        run: |
          echo "// new line $(date -u)" >> daily-log.txt
          git config user.name "stavgian"
          git config user.email "131011025+stavgian@users.noreply.github.com"
          git add daily-log.txt
          git commit -m "chore: daily commit $(date -u)" || exit 0
          git pull --rebase
          git push
